name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v5

      - name: project setup
        run: make setup

      - name: run linter
        run: make lint

      - name: run test
        run: make test
